<a href="https://www.kaggle.com/code/rabiatahmed/best-movies-of-all-time-1989-2021?scriptVersionId=329242733" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# About the project
For this project, I analyzed a dataset containing the best movies of all time to identify trends and patterns. Titles include movies like Spiderman, Pretty Woman, Black Panther, Wonder Woman, Pirates of The Caribbean, Avatar. Most of the movies are highly rated by IMDb, Rotten Tomatoes, Vudu, Metacritic etc.

The time frame of the dataset is from 1989 to 2021. The dataset is from @nimcool on [data.world](http://data.world)

# Clean
Cleaning was done with both Spreadsheets and R. Spreadsheets was used to add the release years to the titles, correct figures, remove an incorrect row, remove a duplicate, and correct a date.

* The release years were added to the titles because figures with similar titles added up when uploaded to Tableau. Also, adding the release years to the titles made it easy to spot patterns. For example, 4 out of the bottom 10 lowest grossing movies were movies released in 2020, this was due to the COVID-19 Pandemic.

* Most of the budget figures and gross figures were obtained from Wikipedia. Some of the figures might not be exactly accurate. It was not stated on Wikipedia if the budget figures included print and advertising cost. Also, some of the budget figures were in ranges. The figures in the dataset that were within the ranges in Wikipedia were not changed, only the figures that were below or above the ranges or different from what is on Wikipedia were changed. It was also not stated if the gross figures included other revenue sources like DVD sales, TV and international rights, streaming platforms etc. And the gross figures were rounded up.

* One movie was removed from the dataset because the budget figure and gross figure were similar and the budget figure was not on Wikipedia or other sites.  A movie was recorded twice, one of them was removed. Another movie had an incorrect date which was corrected.

Both the original dataset and the dataset cleaned with Spreadsheets have been uploaded to Kaggle. Below is the code used to clean the dataset before analyzing and visualizing.

In [1]:
install.packages("tidyverse")
library(tidyverse)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.2

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [2]:
#Load the dataset
library(readr)
bmoat <- read.csv("/kaggle/input/best-movies-of-all-time/best_movies_of_all_time_dirty.csv")

#Display first 5 rows
head(bmoat, 5)

  MovieID Title                                   MPAA_Rating Budget
1  5      Field of Dreams-1989                    PG          15000000
2 18      Indiana Jones and the Last Crusade-1989 PG-13       48000000
3  8      Dead Poets Society-1989                 PG          16400000
4 15      Ghostbusters II-1989                    PG          37000000
5 13      Honey, I Shrunk the Kids-1989           PG          18000000
  Gross     Release_Date Genre     Runtime Rating Rating_Count
1  84400000 4/21/1989    Drama     107     7.5    101702
2 474200000 5/24/1989    Adventure 127     8.2    647495
3 235900000 6/2/1989     Drama     129     8.1    382002
4 215400000 6/15/1989    Comedy    108     6.6    171196
5 222700000 6/22/1989    Family     93     6.3    132480
  Summary
1 An Iowa corn farmer, hearing voices, interprets them as a command to build a baseball diamond in his fields; he does, and the 1919 Chicago White Sox come.
2 In 1938, after his father Professor Henry Jones, Sr. goes missing while pursuing the Holy Grail, Professor Henry Indiana Jones, Jr. finds himself up against Adolf Hitlers Nazis again to stop them from obtaining its powers.
3 English teacher John Keating inspires his students to look at poetry with a different perspective of authentic knowledge and feelings.
4 The discovery of a massive river of ectoplasm and a resurgence of spectral activity allows the staff of Ghostbusters to revive the business.
5 The scientist father of a teenage girl and boy accidentally shrinks his and two other neighborhood teens to the size of insects. Now the teens must fight diminutive dangers as the father searches for them.

In [3]:
#Select columns
bmoat <- bmoat %>% select(Title, Release_Date, MPAA_Rating, Budget, Gross)

head(bmoat, 5)

  Title                                   Release_Date MPAA_Rating Budget
1 Field of Dreams-1989                    4/21/1989    PG          15000000
2 Indiana Jones and the Last Crusade-1989 5/24/1989    PG-13       48000000
3 Dead Poets Society-1989                 6/2/1989     PG          16400000
4 Ghostbusters II-1989                    6/15/1989    PG          37000000
5 Honey, I Shrunk the Kids-1989           6/22/1989    PG          18000000
  Gross
1  84400000
2 474200000
3 235900000
4 215400000
5 222700000

In [4]:
#Change column names to lowercase and rename a column
bmoat <- bmoat %>% rename_with(tolower) %>% rename(age_rating = "mpaa_rating")

In [5]:
#confirm
colnames(bmoat)

[1] "title"        "release_date" "age_rating"   "budget"       "gross"

In [6]:
#Check column data types
glimpse(bmoat)

Rows: 632
Columns: 5
$ title        <chr> "Field of Dreams-1989", "Indiana Jones and the Last Crusa…
$ release_date <chr> "4/21/1989", "5/24/1989", "6/2/1989", "6/15/1989", "6/22/…
$ age_rating   <chr> "PG", "PG-13", "PG", "PG", "PG", "PG", "R", "R", "PG", "P…
$ budget       <int> 15000000, 48000000, 16400000, 37000000, 18000000, 4800000…
$ gross        <dbl> 84400000, 474200000, 235900000, 215400000, 222700000, 411…

In [7]:
#Convert the date column to the appropriate data type
bmoat$release_date <- as.Date(bmoat$release_date, "%m/%d/%Y")

In [8]:
#Confirm
glimpse(bmoat)

Rows: 632
Columns: 5
$ title        <chr> "Field of Dreams-1989", "Indiana Jones and the Last Crusa…
$ release_date <date> 1989-04-21, 1989-05-24, 1989-06-02, 1989-06-15, 1989-06-…
$ age_rating   <chr> "PG", "PG-13", "PG", "PG", "PG", "PG", "R", "R", "PG", "P…
$ budget       <int> 15000000, 48000000, 16400000, 37000000, 18000000, 4800000…
$ gross        <dbl> 84400000, 474200000, 235900000, 215400000, 222700000, 411…

In [9]:
#Check spellings in cell
bmoat %>% count(age_rating)

  age_rating n
1 G           27
2 PG         164
3 PG-13      299
4 R          142

In [10]:
#Arrange dataset by release date
bmoat <- bmoat %>% arrange(release_date)

#Display first 5 rows
head(bmoat, 5)

#Display last 5 rows
tail(bmoat, 5)

  title                                   release_date age_rating budget
1 Field of Dreams-1989                    1989-04-21   PG         15000000
2 Indiana Jones and the Last Crusade-1989 1989-05-24   PG-13      48000000
3 Dead Poets Society-1989                 1989-06-02   PG         16400000
4 Ghostbusters II-1989                    1989-06-15   PG         37000000
5 Honey, I Shrunk the Kids-1989           1989-06-22   PG         18000000
  gross
1  84400000
2 474200000
3 235900000
4 215400000
5 222700000

    title                      release_date age_rating budget    gross
628 Dune-2021                  2021-10-22   PG-13      165000000  402000000
629 tick, tick…BOOM!-2021      2021-11-12   PG-13       55000000     115585
630 Encanto-2021               2021-11-24   PG         150000000  256800000
631 West Side Story-2021       2021-12-10   PG-13      100000000   76000000
632 Spiderman:No Way Home-2021 2021-12-17   PG-13      200000000 1922000000

# Visualize
**This part was done with Tableau**

**Budget vs. Gross**
<div class='tableauPlaceholder' id='viz1781721608988' style='position: relative'><noscript><a href='#'><img alt='bdg vs. gro dashboard ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Be&#47;BestMoviesofAllTime1989-2021&#47;bdgvs_grodashboard&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='BestMoviesofAllTime1989-2021&#47;bdgvs_grodashboard' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Be&#47;BestMoviesofAllTime1989-2021&#47;bdgvs_grodashboard&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='en-US' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1781721608988');                    var vizElement = divElement.getElementsByTagName('object')[0];                    if ( divElement.offsetWidth > 800 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else if ( divElement.offsetWidth > 500 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else { vizElement.style.width='100%';vizElement.style.height='727px';}                     var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>

**Highest Budget vs. Highest Grossing**

<div class='tableauPlaceholder' id='viz1781723247331' style='position: relative'><noscript><a href='#'><img alt='Highest Budget vs. Highest Grossing ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Be&#47;BestMoviesofAllTime1989-2021&#47;Dashboard4&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='BestMoviesofAllTime1989-2021&#47;Dashboard4' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Be&#47;BestMoviesofAllTime1989-2021&#47;Dashboard4&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='en-US' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1781723247331');                    var vizElement = divElement.getElementsByTagName('object')[0];                    if ( divElement.offsetWidth > 800 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else if ( divElement.offsetWidth > 500 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else { vizElement.style.width='100%';vizElement.style.height='727px';}                     var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>

**Lowest Budget vs. Lowest Grossing**

<div class='tableauPlaceholder' id='viz1781719224762' style='position: relative'><noscript><a href='#'><img alt='Lowest Budget vs. Lowest Grossing ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Be&#47;BestMoviesofAllTime1989-2021&#47;LowestBudgetvs_LowestGrossing&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='BestMoviesofAllTime1989-2021&#47;LowestBudgetvs_LowestGrossing' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Be&#47;BestMoviesofAllTime1989-2021&#47;LowestBudgetvs_LowestGrossing&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='en-US' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1781719224762');                    var vizElement = divElement.getElementsByTagName('object')[0];                    if ( divElement.offsetWidth > 800 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else if ( divElement.offsetWidth > 500 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else { vizElement.style.width='100%';vizElement.style.height='727px';}                     var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>

**Trends Over Time**

<div class='tableauPlaceholder' id='viz1781720279322' style='position: relative'><noscript><a href='#'><img alt='Trends Over Time ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Be&#47;BestMoviesofAllTime1989-2021&#47;TrendsOverTime&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='BestMoviesofAllTime1989-2021&#47;TrendsOverTime' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Be&#47;BestMoviesofAllTime1989-2021&#47;TrendsOverTime&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='en-US' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1781720279322');                    var vizElement = divElement.getElementsByTagName('object')[0];                    if ( divElement.offsetWidth > 800 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else if ( divElement.offsetWidth > 500 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else { vizElement.style.width='100%';vizElement.style.height='927px';}                     var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>

**Age Ratings**

<div class='tableauPlaceholder' id='viz1781720863256' style='position: relative'><noscript><a href='#'><img alt='Age Ratings ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Be&#47;BestMoviesofAllTime1989-2021&#47;AgeRatings&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='BestMoviesofAllTime1989-2021&#47;AgeRatings' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Be&#47;BestMoviesofAllTime1989-2021&#47;AgeRatings&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='en-US' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1781720863256');                    var vizElement = divElement.getElementsByTagName('object')[0];                    if ( divElement.offsetWidth > 800 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else if ( divElement.offsetWidth > 500 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else { vizElement.style.width='100%';vizElement.style.height='927px';}                     var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>

**Movie Release Seasons**
<div class='tableauPlaceholder' id='viz1782052509005' style='position: relative'><noscript><a href='#'><img alt='Movie Release Seasons ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Be&#47;BestMoviesofAllTime1989-2021&#47;timeofyear_1&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='BestMoviesofAllTime1989-2021&#47;timeofyear_1' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Be&#47;BestMoviesofAllTime1989-2021&#47;timeofyear_1&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='en-US' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1782052509005');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>

# Findings
1) There is a positive relationship between budget and gross.
2) Avengers: Infinity War-2018, Avenger: Endgame-2019 and Star Wars: The Force Awakens-2015 appeared on both the top 10 highest budget movies chart and the top 10 highest grossing movies chart.
3) The Crying Game-1992 and The Father-2020 appeared on both the bottom 10 lowest budget movies chart and bottom 10 lowest grossing movies chart. Three other movies released in 2020 appeared on the bottom 10 lowest grossing movies chart.
4) Up until 2020, there was a steady increase in average movie budget and average movie gross. 
There was a significant decrease in the number of movies, average budget and average gross in 2020.  The number of movies dropped from 20 to 11, the average budget dropped from \\$138,975,000 \\$to 89,227,273 and the average gross dropped from \\$705,990,000 to \\$207,210,986. The differences are quite huge.
5) G rated movies had the lowest number of movies but had the second highest average budget and second highest average gross. PG-13 rated movies had the highest number of movies, highest averarge budget and highest average gross. PG and R rated movies ranked second and third in number of movies, and third and fourth in both average budget and average gross.
6) Most of the movies were released mid-year and end-of-year.

Explore the [interactive dashboard](http://public.tableau.com/views/BestMoviesofAllTime1989-2021/successfulunsuccessfuldashboard?:language=en-US&:display_count=n&:origin=viz_share_link) that highlights the successful movies and unsuccessful movies.